### ISSUE TITLE
Form validation on contact page

### ISSUE THREAD

**Issue by thijszzz** [thijszzz/thijsbremeesch.be#25]

**Comment by wouterlanduydt** [comment]
Iets specifieker? 😛

**Comment by thijszzz** [comment]
zie sketch file (al eens besproken of vergis ik me?)

**Comment by wouterlanduydt** [comment]
Heb je het over de form validation op de contact page?

**Comment by thijszzz** [comment]
jaaa form validation da woord zocht ik!!
